version: "3"

services: 
  mysql-server:
    image: mysql:5.7 
    volume: /home/rglr/data/db:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE="zabbix" 
      - MYSQL_USER="zabbix" 
      - MYSQL_PASSWORD="zabbix_pwd"
      - MYSQL_ROOT_PASSWORD="root_pwd"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:latest

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:latest
    environment: 
      - DB_SERVER_HOST="mysql-server" 
      - MYSQL_DATABASE="zabbix" 
      - MYSQL_USER="zabbix" 
      - MYSQL_PASSWORD="zabbix_pwd" 
      - MYSQL_ROOT_PASSWORD="root_pwd" 
      - ZBX_JAVAGATEWAY="zabbix-java-gateway" 
    links: 
      - "mysql-server:mysql"
      - "zabbix-server-mysql:zabbix-server"
    ports:
      - 10051:10051


  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    enviroment:
      - DB_SERVER_HOST="mysql-server" \
      - MYSQL_DATABASE="zabbix" \
      - MYSQL_USER="zabbix" \
      - MYSQL_PASSWORD="zabbix_pwd" \
      - MYSQL_ROOT_PASSWORD="root_pwd" \
    ports:
      - 80:80
    links:
      - "mysql-server:mysql"
      - "zabbix-server-mysql:zabbix-server"

